CREATE TABLE GRT_EVENTS (
  ID VARCHAR(36) NOT NULL PRIMARY KEY,
  VERSION INTEGER,
  CONTEXT VARCHAR(64) NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  STATUS VARCHAR(16) NOT NULL,
  RAISED_AT TIMESTAMP NOT NULL,
  FORWARDED_AT TIMESTAMP,
  CONSUMED_AT TIMESTAMP,
  PROCESSED_AT TIMESTAMP,
  RAISED_BY_COMMAND VARCHAR(36),
  RAISED_BY_FLOW VARCHAR(36),
  AGGREGATE_ID VARCHAR(36) NOT NULL,
  AGGREGATE_NAME VARCHAR(128) NOT NULL,
  AGGREGATE_VERSION INTEGER NOT NULL,
  JSON TEXT NOT NULL
)
