version: '3'
services:   
  gr:
    image: plexiti/greetings:latest
    ports:
      - "80:8080"
    depends_on:
      - db
      - mq
    networks:
      - mq
      - db
    volumes:
      - ./greetings/.greetings/:/mnt/.greetings
  mq:
    image: rabbitmq:3.6.10-management-alpine
    ports:
      - "5672"
      - "15672:15672"
    networks:
      - mq
  db:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=greetings
      - POSTGRES_USER=greetings
      - POSTGRES_DB=greetings
    volumes:
      - db:/var/lib/postgresql/data
  fl:
    image: camunda/camunda-bpm-platform:7.7.0
    ports:
      - "8080:8080"
    networks:
      - db
      - mq
    depends_on:
      - db
      - mq
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db/greetings
      - DB_USERNAME=greetings
      - DB_PASSWORD=greetings
      - TZ=Europe/Berlin
    volumes:
      - ./.camunda/webapps/camunda-invoice:/camunda/webapps/camunda-invoice
      - ./.camunda/conf:/camunda/conf
networks:
  mq:
    driver: bridge
  db:
    driver: bridge
volumes:
  db:
