version: '3'
services:
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - gr
    networks:
      - lb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gr:
    image: plexiti/greetings
    ports:
      - "8080"
    depends_on:
      - db
      - mq
      - fl
    networks:
      - lb
      - mq
      - db
    volumes:
      - ./app/.greetings/:/mnt/.greetings
  mq:
    image: rabbitmq:management
    ports:
      - "5672"
      - "15672:15672"
    networks:
      - mq
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      - POSTGRES_PASSWORD=greetings
      - POSTGRES_USER=greetings
      - POSTGRES_DB=greetings
    volumes:
      - db:/var/lib/postgresql/data
  fl:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8080:8080"
    networks:
      - db
      - mq
    depends_on:
      - db
      - mq
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db/greetings
      - DB_USERNAME=greetings
      - DB_PASSWORD=greetings
      - TZ=Europe/Berlin
    volumes:
      - ./.camunda/webapps/camunda-invoice:/camunda/webapps/camunda-invoice
      - ./.camunda/conf:/camunda/conf
networks:
  lb:
    driver: bridge
  mq:
    driver: bridge
  db:
    driver: bridge
volumes:
  db:
